import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#a9c7ff",
        "on-tertiary": "#2f3131",
        "surface": "#131313",
        "on-primary-fixed": "#001b3d",
        "on-primary-container": "#002957",
        "surface-dim": "#131313",
        "on-tertiary-container": "#282a2a",
        "on-error": "#690005",
        "outline-variant": "#404754",
        "on-secondary-fixed-variant": "#544600",
        "background": "#131313",
        "tertiary-fixed": "#e2e2e2",
        "surface-container-highest": "#353534",
        "on-secondary-fixed": "#221b00",
        "primary-fixed": "#d6e3ff",
        "surface-container-high": "#2a2a2a",
        "on-secondary-container": "#725f00",
        "error-container": "#93000a",
        "surface-variant": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed": "#1a1c1c",
        "inverse-on-surface": "#313030",
        "secondary-fixed-dim": "#e9c400",
        "primary": "#a9c7ff",
        "tertiary": "#c6c6c7",
        "primary-container": "#3a90ff",
        "on-primary-fixed-variant": "#00468b",
        "on-background": "#e5e2e1",
        "surface-tint": "#a9c7ff",
        "surface-container": "#201f1f",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-primary": "#003063",
        "on-surface-variant": "#c0c6d6",
        "tertiary-container": "#909191",
        "on-surface": "#e5e2e1",
        "on-secondary": "#3a3000",
        "secondary": "#fff9ef",
        "inverse-surface": "#e5e2e1",
        "inverse-primary": "#005db6",
        "surface-bright": "#3a3939",
        "outline": "#8a91a0",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#454747",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#1c1b1b",
        "secondary-fixed": "#ffe16d",
        "secondary-container": "#ffdb3c",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "#0085FF",
          foreground: "#ffffff",
          container: "#3a90ff",
        },
        gold: {
          DEFAULT: "#FFD700",
          dim: "#e9c400",
        },
        surface: {
          DEFAULT: "#131313",
          dim: "#131313",
          bright: "#393939",
          container: "#1f1f1f",
          "container-low": "#1b1b1b",
          "container-high": "#2a2a2a",
          "container-highest": "#353535",
          "container-lowest": "#0e0e0e",
          variant: "#353535",
        },
        card: {
          DEFAULT: "#111827",
          foreground: "#f9fafb",
        },
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
export default config;
