-- Run this in your Supabase SQL Editor FIRST to add ALL possible missing columns!
-- =========================================================================

-- COHORT COLUMNS (Brute force apply all)
ALTER TABLE "Cohort" ADD COLUMN IF NOT EXISTS "slug" TEXT;
ALTER TABLE "Cohort" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "Cohort" ADD COLUMN IF NOT EXISTS "tagline" TEXT;
ALTER TABLE "Cohort" ADD COLUMN IF NOT EXISTS "heroTitle" TEXT;
ALTER TABLE "Cohort" ADD COLUMN IF NOT EXISTS "heroHighlight" TEXT;
ALTER TABLE "Cohort" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "Cohort" ADD COLUMN IF NOT EXISTS "accentColor" TEXT;
ALTER TABLE "Cohort" ADD COLUMN IF NOT EXISTS "accentHex" TEXT;
ALTER TABLE "Cohort" ADD COLUMN IF NOT EXISTS "logoUrl" TEXT;
ALTER TABLE "Cohort" ADD COLUMN IF NOT EXISTS "bannerUrl" TEXT;
ALTER TABLE "Cohort" ADD COLUMN IF NOT EXISTS "emoji" TEXT;
ALTER TABLE "Cohort" ADD COLUMN IF NOT EXISTS "discordLink" TEXT;
ALTER TABLE "Cohort" ADD COLUMN IF NOT EXISTS "whatsappLink" TEXT;
ALTER TABLE "Cohort" ADD COLUMN IF NOT EXISTS "lumaCalendarUrl" TEXT;
ALTER TABLE "Cohort" ADD COLUMN IF NOT EXISTS "features" JSONB;
ALTER TABLE "Cohort" ADD COLUMN IF NOT EXISTS "faqs" JSONB;
ALTER TABLE "Cohort" ADD COLUMN IF NOT EXISTS "testimonials" JSONB;
ALTER TABLE "Cohort" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN DEFAULT true;

-- BUNDLE COLUMNS (Brute force apply all)
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "slug" TEXT;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "cohortSlug" TEXT;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "tagline" TEXT;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "originalPrice" DOUBLE PRECISION;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "eventPrice" DOUBLE PRECISION;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "isDiscounted" BOOLEAN DEFAULT false;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "isPrimary" BOOLEAN DEFAULT false;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'DRAFT';
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "difficultyLevel" TEXT;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "duration" TEXT;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "startDate" TEXT;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "schedule" TEXT;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "registrationDeadline" TIMESTAMP(3);
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "maxSeats" INTEGER;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "seatsLeft" INTEGER;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "instructorName" TEXT;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "instructorRole" TEXT;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "instructorAvatarUrl" TEXT;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "demoVideoUrl" TEXT;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "certificateIncluded" BOOLEAN DEFAULT true;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "features" JSONB;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "highlights" JSONB;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "curriculum" JSONB;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "outcomes" JSONB;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "prerequisites" JSONB;
ALTER TABLE "Bundle" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN DEFAULT true;
