-- ==========================================
-- COHORT DATA SEED MIGRATION
-- Run this in your Supabase SQL Editor
-- ==========================================

-- Insert Cohorts
INSERT INTO "Cohort" ("id", "slug", "name", "tagline", "heroTitle", "heroHighlight", "description", "accentColor", "accentHex", "emoji", "logoUrl", "features")
VALUES 
(gen_random_uuid(), 'opensource', 'Open Source', 'Production-ready workshops to help you contribute to the world''s most impactful software.', 'Master', 'Open Source.', 'Level up your open source journey with Revamp. GSoC prep, first contributions, and advanced open source skills.', '217 91% 60%', '#3b82f6', '🔓', 'https://ik.imagekit.io/cotszrkgk/Screenshot_2025-06-25_at_9.10.56_PM-removebg-preview.png?updatedAt=1756648034230', '[{"title": "Secure Infrastructure", "description": "Enterprise-grade security for 100k users. Payments powered by Razorpay.", "icon": "shield"}, {"title": "Referral Network", "description": "Boost your impact. Join our referral program and lead the open source movement.", "icon": "users"}, {"title": "Proven Curriculum", "description": "Battle-tested workshops designed for real-world contributions and GSoC success.", "icon": "award"}]'::jsonb),
(gen_random_uuid(), 'webdev', 'Web Development', 'Build production-ready web apps from scratch. HTML, CSS, JS, React — the full stack.', 'Build The', 'Modern Web.', 'Master web development from fundamentals to full-stack. Build real projects, deploy live sites, and launch your dev career.', '263 70% 58%', '#8b5cf6', '🌐', null, '[{"title": "Project-Based Learning", "description": "Build 5+ real projects — a portfolio, a dashboard, an API integration — not toy apps.", "icon": "code"}, {"title": "Live Portfolio", "description": "Deploy your personal site to GitHub Pages. Walk out with a live URL and real projects.", "icon": "globe"}, {"title": "Industry Tools", "description": "Learn the tools real devs use: VS Code, Git, Chrome DevTools, npm, and Vercel.", "icon": "wrench"}]'::jsonb),
(gen_random_uuid(), 'aiml', 'AI & ML', 'Master Vibe Coding, LangChain, n8n automation, and build real AI-powered apps.', 'Master', 'Agentic AI.', 'Build AI agents, automate workflows, and learn LangChain in this hands-on cohort. Ship 10+ AI projects.', '160 84% 39%', '#10b981', '🤖', null, '[{"title": "10+ AI Projects", "description": "Build chatbots, agents, automations, and AI tools you can actually use and showcase.", "icon": "brain"}, {"title": "No-Code + Code", "description": "Learn both n8n automation and LangChain/Python — pick your path or master both.", "icon": "workflow"}, {"title": "Live Weekend Sessions", "description": "Live coding sessions every weekend with Q&A, code reviews, and project showcases.", "icon": "video"}]'::jsonb),
(gen_random_uuid(), 'launchpad', 'College Starter', 'You just got into B.Tech. You have 4 months before Day 1. This is how you use them.', 'Start College', 'Ahead.', 'The 4-week pre-college program that gives B.Tech freshers a headstart — real skills, real friends, real projects before Day 1.', '38 92% 50%', '#f59e0b', '🚀', null, '[{"title": "Find Your People", "description": "Speed-friending, team builds, and a cohort network that lasts all 4 years of college. Go to hackathons together.", "icon": "users"}, {"title": "Technical Headstart", "description": "Terminal, Git, Python, HTML/CSS — the 20% of skills that unlock 80% of college CS. Arrive knowing more than most seniors.", "icon": "code"}, {"title": "Ship Something Real", "description": "A 48-hour mini hackathon in Week 3. Build with your team, demo on stage, and deploy your first real project.", "icon": "rocket"}]'::jsonb),
(gen_random_uuid(), 'cp', 'Competitive Programming', 'Crack DSA, ace coding interviews, and dominate competitive programming contests.', 'Dominate', 'Competitions.', 'Master algorithms, data structures, and competitive programming. Prepare for coding contests and tech interviews.', '0 84% 60%', '#ef4444', '⚔️', null, '[{"title": "Contest Ready", "description": "Practice with real contest problems from Codeforces, LeetCode, and CodeChef.", "icon": "trophy"}, {"title": "DSA Mastery", "description": "Master arrays, trees, graphs, DP, and more with structured problem sets.", "icon": "binary"}, {"title": "Interview Prep", "description": "FAANG-style mock interviews and coding challenges to ace your placements.", "icon": "briefcase"}]'::jsonb),
(gen_random_uuid(), 'cybersec', 'Cyber Security', 'Defend the grid. Ethical hacking, CTFs, and real-world security — the hacker mindset, the right way.', 'Defend The', 'Grid.', 'Learn ethical hacking, network defense, and web app security. Compete in CTFs, find vulnerabilities, and build a security portfolio.', '192 91% 42%', '#06b6d4', '🛡️', null, '[{"title": "Hands-On Hacking", "description": "Practice on real vulnerable machines. Kali Linux, Burp Suite, Metasploit — the real tools, learned properly.", "icon": "shield"}, {"title": "CTF Competitions", "description": "Compete in Capture The Flag challenges every week. Web exploitation, cryptography, forensics, and reverse engineering.", "icon": "trophy"}, {"title": "Career-Ready Skills", "description": "SOC analyst, penetration tester, or bug bounty hunter — build the portfolio and certs that actually get you hired.", "icon": "briefcase"}]'::jsonb)
ON CONFLICT ("slug") DO UPDATE 
SET "name" = EXCLUDED."name",
    "tagline" = EXCLUDED."tagline",
    "heroTitle" = EXCLUDED."heroTitle",
    "heroHighlight" = EXCLUDED."heroHighlight",
    "description" = EXCLUDED."description",
    "accentColor" = EXCLUDED."accentColor",
    "accentHex" = EXCLUDED."accentHex",
    "emoji" = EXCLUDED."emoji",
    "features" = EXCLUDED."features";

-- Insert Bundles
INSERT INTO "Bundle" ("id", "slug", "cohortSlug", "name", "tagline", "originalPrice", "eventPrice", "isDiscounted", "isPrimary", "duration", "startDate", "schedule", "maxSeats", "seatsLeft", "highlights", "curriculum", "outcomes")
VALUES 
-- OPEN SOURCE
(gen_random_uuid(), 'gsoc-intensive', 'opensource', 'GSOC INTENSIVE', 'Your complete roadmap to getting selected in Google Summer of Code', 1999, 999, true, true, '4 Weeks', 'March 1, 2026', 'Weekends — Sat & Sun, 7 PM - 9 PM IST', 50, 18, '["Live mentoring from past GSoC contributors", "End-to-end proposal writing workshop", "Real org codebase walkthrough", "Mock proposal review sessions"]'::jsonb, '[{"week": "Week 1", "title": "Understanding GSoC"}, {"week": "Week 2", "title": "Finding Your Organization"}, {"week": "Week 3", "title": "Proposal Masterclass"}, {"week": "Week 4", "title": "Final Push & Submission"}]'::jsonb, '["A submission-ready GSoC proposal", "Contributions to a real open source organization"]'::jsonb),
(gen_random_uuid(), 'opensource-starter', 'opensource', 'OPENSOURCE STARTER', 'Go from zero to your first open source contribution in 2 weeks', 1499, 699, true, false, '2 Weeks', 'March 1, 2026', 'Weekends — Sat & Sun, 5 PM - 7 PM IST', 80, 34, '["Beginner-friendly — no prior experience needed", "Hands-on Git & GitHub workflow training"]'::jsonb, '[{"week": "Week 1", "title": "Git, GitHub & Open Source 101"}, {"week": "Week 2", "title": "Your First Contribution"}]'::jsonb, '["Solid Git & GitHub skills", "At least one merged PR on a real project"]'::jsonb),
(gen_random_uuid(), 'opensource-specific', 'opensource', 'OPENSOURCE SPECIFIC', 'Deep-dive into a specific organization and become a core contributor', 1500, 1500, false, false, '3 Weeks', 'March 8, 2026', 'Flexible — Self-paced with weekly live Q&A', 30, 12, '["Choose your target organization", "Personalized mentoring for your tech stack"]'::jsonb, '[{"week": "Week 1", "title": "Deep Dive into Your Org"}]'::jsonb, '["Multiple contributions to your chosen organization"]'::jsonb),

-- WEB DEV
(gen_random_uuid(), 'fullstack-foundations', 'webdev', 'FULLSTACK FOUNDATIONS', 'Go from zero to building real web applications in 4 weeks', 1999, 999, true, true, '4 Weeks', 'April 5, 2026', 'Weekends — Sat & Sun, 6 PM - 8 PM IST', 60, 25, '["Build 4 real projects from scratch", "Master HTML, CSS, JavaScript, and React"]'::jsonb, '[{"week": "Week 1", "title": "Web Fundamentals"}]'::jsonb, '["4 deployed web projects", "Strong HTML/CSS/JS + React skills"]'::jsonb),
(gen_random_uuid(), 'frontend-mastery', 'webdev', 'FRONTEND MASTERY', 'Level up your frontend skills with advanced CSS, animations, and architecture', 1499, 699, true, false, '2 Weeks', 'April 5, 2026', 'Weekends — Sat & Sun, 4 PM - 6 PM IST', 40, 20, '["Master advanced CSS techniques", "Build smooth animations & transitions"]'::jsonb, '[{"week": "Week 1", "title": "Advanced CSS & Design"}]'::jsonb, '["Advanced CSS skills", "Portfolio-quality animated components"]'::jsonb),
(gen_random_uuid(), 'portfolio-bootcamp', 'webdev', 'PORTFOLIO BOOTCAMP', 'Build and deploy a stunning personal portfolio in one intensive weekend', 999, 499, true, false, '1 Week', 'April 12, 2026', 'Saturday, 10 AM - 6 PM IST (Full Day)', 80, 45, '["One-day intensive workshop", "Template to customize"]'::jsonb, '[{"week": "Day 1", "title": "Build & Deploy"}]'::jsonb, '["A live portfolio website", "GitHub Pages deployment skills"]'::jsonb),

-- AI & ML
(gen_random_uuid(), 'agentic-ai-builder', 'aiml', 'AGENTIC AI BUILDER', 'Build production-ready AI agents with LangChain, RAG, and modern AI tools', 2499, 1299, true, true, '4 Weeks', 'April 5, 2026', 'Weekends — Sat & Sun, 7 PM - 9 PM IST', 40, 15, '["Hands-on LangChain & LangGraph", "Build 5 real AI agents"]'::jsonb, '[{"week": "Week 1", "title": "AI Foundations"}]'::jsonb, '["5 deployed AI agents", "LangChain & LangGraph mastery"]'::jsonb),
(gen_random_uuid(), 'vibe-coding-starter', 'aiml', 'VIBE CODING STARTER', 'Learn to build with AI — prompt engineering, ChatGPT API, and AI-assisted coding', 1499, 699, true, false, '2 Weeks', 'April 5, 2026', 'Weekends — Sat & Sun, 5 PM - 7 PM IST', 60, 30, '["AI-powered development", "Prompt engineering deep dive"]'::jsonb, '[{"week": "Week 1", "title": "AI-Assisted Development"}]'::jsonb, '["AI-assisted coding skills", "Prompt engineering mastery"]'::jsonb),
(gen_random_uuid(), 'n8n-automation', 'aiml', 'N8N AUTOMATION', 'Automate everything — build workflows, integrate APIs, and scale operations', 1299, 599, true, false, '2 Weeks', 'April 12, 2026', 'Weekends — Sat, 4 PM - 7 PM IST', 50, 22, '["No-code workflow builder", "20+ integration templates"]'::jsonb, '[{"week": "Week 1", "title": "n8n Fundamentals"}]'::jsonb, '["10+ automation workflows", "API integration mastery"]'::jsonb),

-- COLLEGE STARTER
(gen_random_uuid(), 'college-starter', 'launchpad', 'COLLEGE STARTER', '4 weeks. Real skills. Real friends. Walk into college like you belong.', 1999, 999, true, true, '4 Weeks', 'May 10, 2026', '2-3 sessions/week — 7 PM - 9 PM IST', 50, 22, '["Speed-friending + cohort bonding from Day 1", "Terminal, Git, Python & Web — hands-on, not theory"]'::jsonb, '[{"week": "Week 1", "title": "Orientation & Foundations"}]'::jsonb, '["A GitHub profile with real projects", "A team of peers for hackathons & startups"]'::jsonb),
(gen_random_uuid(), 'tech-foundations', 'launchpad', 'TECH FOUNDATIONS', 'Learn the technical skills that separate ''just enrolled'' from ''already building''', 1499, 699, true, false, '2 Weeks', 'May 10, 2026', 'Self-paced + 2 live sessions/week', 80, 40, '[]'::jsonb, '[{"week": "Week 1", "title": "Terminal, Linux & Networking"}]'::jsonb, '["Command line confidence", "Git & GitHub portfolio"]'::jsonb),
(gen_random_uuid(), 'hackathon-prep', 'launchpad', 'HACKATHON PREP', 'Form a team, build a project, demo on stage — your first hackathon experience', 999, 499, true, false, '2 Weeks', 'May 24, 2026', '1 live session/week + 48-hour hackathon', 60, 30, '[]'::jsonb, '[{"week": "Week 1", "title": "Ideation & Team Build"}]'::jsonb, '["A shipped project with a demo video"]'::jsonb),

-- COMPETITIVE PROGRAMMING
(gen_random_uuid(), 'algorithm-mastery', 'cp', 'ALGORITHM MASTERY', 'Master advanced algorithms and data structures for contests and interviews', 1999, 999, true, true, '4 Weeks', 'April 5, 2026', 'Weekends — Sat & Sun, 8 PM - 10 PM IST', 50, 20, '[]'::jsonb, '[{"week": "Week 1", "title": "Foundations & Sorting"}]'::jsonb, '["50+ problems solved", "Advanced algorithm skills"]'::jsonb),
(gen_random_uuid(), 'contest-prep', 'cp', 'CONTEST PREP', 'Level up your Codeforces/LeetCode rating and dominate online contests', 1499, 699, true, false, '3 Weeks', 'April 5, 2026', 'Weekends — Sat, 7 PM - 10 PM IST', 40, 15, '[]'::jsonb, '[{"week": "Week 1", "title": "Pattern Recognition"}]'::jsonb, '["Improved contest rating", "Faster problem solving"]'::jsonb),
(gen_random_uuid(), 'dsa-bootcamp', 'cp', 'DSA BOOTCAMP', 'Build a solid foundation in data structures and algorithms from scratch', 1299, 599, true, false, '2 Weeks', 'April 12, 2026', 'Weekends — Sat & Sun, 5 PM - 7 PM IST', 80, 40, '[]'::jsonb, '[{"week": "Week 1", "title": "Linear Data Structures"}]'::jsonb, '["Solid DSA fundamentals", "30+ problems solved"]'::jsonb),

-- CYBER SECURITY
(gen_random_uuid(), 'ethical-hacking', 'cybersec', 'ETHICAL HACKING', 'The Ultimate 30-Day Cybersecurity Bootcamp. Go from beginner to discovering real vulnerabilities.', 1999, 999, true, true, '30 Days', 'July 15, 2025', 'Weekends — Sat & Sun, 7 PM - 9 PM IST', 150, 42, '[]'::jsonb, '[{"week": "Week 1", "title": "The Hacker Foundation"}]'::jsonb, '["Find your first valid vulnerability", "Command line and Kali Linux fluency"]'::jsonb),
(gen_random_uuid(), 'network-defense', 'cybersec', 'NETWORK DEFENSE', 'Learn to protect what others try to break — defensive security from day one', 1499, 699, true, false, '2 Weeks', 'April 5, 2026', 'Weekends — Sat & Sun, 5 PM - 7 PM IST', 50, 25, '[]'::jsonb, '[{"week": "Week 1", "title": "Defense Fundamentals"}]'::jsonb, '["Network defense architecture skills", "IDS/IPS configuration ability"]'::jsonb),
(gen_random_uuid(), 'ctf-bootcamp', 'cybersec', 'CTF BOOTCAMP', 'Capture flags, solve puzzles, break codes — competitive security at its finest', 999, 499, true, false, '2 Weeks', 'April 12, 2026', 'Weekends — Sat, 6 PM - 9 PM IST', 60, 30, '[]'::jsonb, '[{"week": "Week 1", "title": "CTF Foundations"}]'::jsonb, '["CTF competition confidence", "Web exploitation skills"]'::jsonb)
ON CONFLICT ("slug") DO UPDATE 
SET "name" = EXCLUDED."name",
    "tagline" = EXCLUDED."tagline",
    "originalPrice" = EXCLUDED."originalPrice",
    "eventPrice" = EXCLUDED."eventPrice",
    "isDiscounted" = EXCLUDED."isDiscounted",
    "isPrimary" = EXCLUDED."isPrimary",
    "duration" = EXCLUDED."duration",
    "startDate" = EXCLUDED."startDate",
    "schedule" = EXCLUDED."schedule",
    "maxSeats" = EXCLUDED."maxSeats",
    "seatsLeft" = EXCLUDED."seatsLeft";
